services:
  app:
    container_name: fjmserver-container
    build: .
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config: